# Use an official Node.js runtime as a parent image
FROM node:18-alpine

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install any needed packages
RUN npm install

# Bundle app source
COPY . .

# Use the SERVER_PORT environment variable
ENV PORT=${SERVER_PORT:-3001}

# Expose the port defined in the environment variable
EXPOSE ${PORT}

# Define the command to run your app
CMD ["node", "server.js"]
